{
 "title": "Systemd-Exporter",
 "tags": [
  "10.4.60.1",
  "<Project-Name>",
  "<Env>",
  "Systemd-Services"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "service_name",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Service Availability",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_state{name=~\"api-gateway.service|node_exporter.service|otp-service.service|redis.service.d|redis-sentinel.service.d|user-management.service\",state=\"active\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU usage per Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(systemd_process_cpu_seconds_total{name=~\"api-gateway.service|node_exporter.service|otp-service.service|redis.service.d|redis-sentinel.service.d|user-management.service\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Service (Detailed)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "systemd_process_resident_memory_bytes{name=~\"api-gateway.service|node_exporter.service|otp-service.service|redis.service.d|redis-sentinel.service.d|user-management.service\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Service Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{job=\"systemd-journal\", service_name=~\"$service_name\"}"
    }
   ]
  }
 ]
}