---
# Frontend Tier - PHP Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: guestbook
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
      - name: php-frontend-container
        image: gcr.io/google-samples/gb-frontend@sha256:a908df8486ff66f2c4daa0d3d8a2fa09846a1fc8efd65649c0109695c7c5cbff
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
        env:
        - name: GET_HOSTS_FROM
          value: "dns"

---
# Frontend Tier - PHP Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: guestbook
    tier: frontend
spec:
  type: NodePort
  selector:
    app: guestbook
    tier: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30009


## command to run this file
# kubectl apply -f fe-deployment.yml

## Check the deployment and service
# kubectl get deployments -l app=guestbook,tier=frontend
# kubectl get services -l app=guestbook,tier=frontend

## Access the frontend application
# Get the external IP of the cluster (if using a cloud provider)
# Then access the application at http://<external-ip>:30009

# If we are on a Local Machine (Minikube)
# minikube service frontend-service --url

## Cleanup resources
# kubectl delete -f fe-deployment.yml
