apiVersion: v1
kind: Pod
metadata:
  name: beta-secret
spec:
  containers:
  - name: beta-secret-container
    image: fedora:latest
    command: ["/bin/bash", "-c", "sleep 3600"]
    volumeMounts:
    - name: beta-secret-volume
      mountPath: /opt/beta-secret
      readOnly: true
  volumes:
  - name: beta-secret-volume
    secret:
      secretName: beta-secret


## Command to create the secret:
# kubectl create secret generic beta-secret --from-file=./1-beta-secret.txt

## To check the content of the secret, you can use the following command:
# kubectl get secret beta-secret -o yaml

## Command to create the pod:
# kubectl apply -f 1-beta-secret-pod.yml

## To check the content of the secret from within the pod, you can use the following command:
# kubectl exec -it beta-secret -c beta-secret-container -- cat /opt/beta-secret/1-beta-secret.txt

## Clean up resources:
# kubectl delete pod beta-secret
# kubectl delete secret beta-secret